### ISSUE TITLE
Allow specifying the target to run the test with

### ISSUE THREAD

**Issue by MOZGIII** [taiki-e/cargo-hack#136]
Some context first: we are building a blockchain on [substrate](https://github.com/paritytech/substrate), and have a monorepo with a bunch of crates. Some crates are intended to be built in both std and `no_std` modes, but the issue is that when building in `no_std` mode, wasm target is assumed. Crates have an `std` flag, which enables std mode in dependencies, and when it's absent - the dependent crates also disable std mode (and switch to assuming `wasm`).
The problem is we can't test `no_std` mode with `cargo hack`.

It would be great if we could use a presence of a certain feature in the features set under test to use a different compile `target` (in our case - `wasm32-unknown-unknown`).

**Comment by taiki-e** [comment]
Do you mean you need an option to process the following two lines in one line?

```sh
cargo hack check --each-feature
cargo hack check --each-feature --skip std --target wasm32-unknown-unknown
```

**Comment by MOZGIII** [comment]
Those two lines are not going to cut it. What they don't handle is:

1. We don't need all crates to be tested under `wasm32-unknown-unknown` - some of them simply don't support `no_std`. yet, some of them work in both `std` and `no_std` mode. When we work at `no_std` mode, we always work in wasm.
2. When we test in the `std` mode, the tests still choose `feat2`, which is only supposed to work in `no_std` mode; we have to list all such features in the command, which works but is messy and hard to maintain: `cargo hack check --feature-powerset --no-dev-deps --exclude-no-default-features --skip runtime-benchmarks --skip try-runtime ...`.

**Comment by MOZGIII** [comment]
Overall, I think baking in the logic to derive target from a feature is kind of overly specific, but I've figured that each crate can have some instructions on how it should be tested by `cargo-hack` in it's `Cargo.toml` metadata.
What if we add some extra information there?

**Comment by taiki-e** [comment]
Thanks for the explanation. If I understand correctly, what this feature request is asking for is something like:

- A way to specify options such as --exclude and --skip per-crate (optionally per-target).

  The package.metadata in Cargo.toml seems to be a reasonable choice, since it can get as json via cargo-metadata.

  Something like the following:

  ```toml
  # Default options if no per-target option is specified.
  [package.metadata.cargo-hack]
  skip = ["feat1"]
  exclude = false # If true, same as `--exclude crate_name`
  
  # Options when built for specific target (wasm32-unknown-unknown, in this case)
  [package.metadata.cargo-hack.target.wasm32-unknown-unknown]
  skip = ["std"]
  ```

---

And the following is the feature that I initially thought this feature request to be asking for.

- A way to handle multiple targets in one command.

  For this, cargo already has two unsettling features.

  - [multitarget](https://doc.rust-lang.org/cargo/reference/unstable.html#multitarget)
  - [per-package-target](https://doc.rust-lang.org/cargo/reference/unstable.html#per-package-target)

  Implementing an ability that emulates multitarget is okay, but this ability does not seem to be a blocker to meet this feature request.
