### ISSUE TITLE
0.6.6 breaks compatibility pipping to formatter in CI

### ISSUE THREAD

**Issue by PKilcommons** [taiki-e/cargo-hack#221]
I am unsure if this issue makes more sense here or on [install-action](https://github.com/taiki-e/install-action) so please let me know if I should close this issue and reopen over there.

At the risk of this sounding like [xkcd 1172](https://xkcd.com/1172/), I was wondering if an option could be provided to disable the grouping behaviour added in #219. In our CI we use [cargo-action-fmt](https://github.com/olix0r/cargo-action-fmt/) to provide Github Action formatting for `clippy`. This worked seamlessly with `taiki-e/install-action@cargo-hack`, but since v0.6.6 piping to `cargo-action-fmt` now breaks the pipe. For now we're pinning to v0.6.5.

Here's the job without pinning to v0.6.5 if that helps at all.
```yml
    steps:
    - uses: actions/checkout@v4

    - name: Sccache Setup
      uses: mozilla-actions/sccache-action@v0.0.3
      with:
        version: "v0.5.3"

    - name: Install nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: clippy, rustfmt

    - name: Install cargo-hack
      uses: taiki-e/install-action@cargo-hack

    - uses: olix0r/cargo-action-fmt/setup@v2

    - name: Check clippy
      run: cargo hack clippy --all-targets --feature-powerset --message-format=json -Zlints -- -Dwarnings -Adeprecated | cargo-action-fmt

    - name: Check rustfmt
      if: success() || failure()
      run: cargo fmt --all -- --check

```

If this is not something you wish to support or if there is an existing workaround that I am not aware of, please do let me know.
