### ISSUE TITLE
A flag to run targets separately?

### ISSUE THREAD

**Issue by jaskij** [taiki-e/cargo-hack#277]
Today, I got bitten by running `cargo hack check --all-targets`, which caused Cargo to unify dependencies between the main library and dev dependencies - a dev dependency pulled in a feature required by the main lib.

Right now, I changed the task to be:

```yaml
tasks:
  check:
    cmds:
      - cargo hack --each-feature check
      - cargo hack --each-feature check --lib
      - cargo hack --each-feature check --bins
      - cargo hack --each-feature check --tests
      - cargo hack --each-feature check --benches
      - cargo hack --each-feature check --examples
```

It would be amazing if `cargo-hack` either:

- changed the behavior of `--all-targets`
- provided a flag to run the checks on all the options, similar to what I did in my CI
