### ISSUE TITLE
request: some sort of argument to add "optional" deps as features

### ISSUE THREAD

**Issue by kentfredric** [taiki-e/cargo-hack#28]
Any time an optional dependency is specified, that internally becomes visible as a feature flag, eg:

```toml
[dependencies.foo]
version = "1.0"
optional = true
```

Can of course, be enabled with `--features foo`

And rust code can check for it with
```rust
#[cfg(feature = "foo")]
```

And code can activate that path via

```toml
[dependencies.bar]
features = ["foo"]
```

Subsequently, it would be nice to have, at least as an option, these hidden features in `--each-feature` and `--feature-powerset` to test for this case.
